/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedMarketplaceRouteImport } from './routes/_authenticated/marketplace'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDealsIndexRouteImport } from './routes/_authenticated/deals/index'
import { Route as AuthenticatedBuyersIndexRouteImport } from './routes/_authenticated/buyers/index'
import { Route as AuthenticatedDealsNewRouteImport } from './routes/_authenticated/deals/new'
import { Route as AuthenticatedDealsIdRouteImport } from './routes/_authenticated/deals/$id'
import { Route as AuthenticatedBuyersNewRouteImport } from './routes/_authenticated/buyers/new'
import { Route as AuthenticatedBuyersIdRouteImport } from './routes/_authenticated/buyers/$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketplaceRoute =
  AuthenticatedMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDealsIndexRoute = AuthenticatedDealsIndexRouteImport.update({
  id: '/deals/',
  path: '/deals/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBuyersIndexRoute =
  AuthenticatedBuyersIndexRouteImport.update({
    id: '/buyers/',
    path: '/buyers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDealsNewRoute = AuthenticatedDealsNewRouteImport.update({
  id: '/deals/new',
  path: '/deals/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDealsIdRoute = AuthenticatedDealsIdRouteImport.update({
  id: '/deals/$id',
  path: '/deals/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBuyersNewRoute = AuthenticatedBuyersNewRouteImport.update({
  id: '/buyers/new',
  path: '/buyers/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBuyersIdRoute = AuthenticatedBuyersIdRouteImport.update({
  id: '/buyers/$id',
  path: '/buyers/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/buyers/$id': typeof AuthenticatedBuyersIdRoute
  '/buyers/new': typeof AuthenticatedBuyersNewRoute
  '/deals/$id': typeof AuthenticatedDealsIdRoute
  '/deals/new': typeof AuthenticatedDealsNewRoute
  '/buyers/': typeof AuthenticatedBuyersIndexRoute
  '/deals/': typeof AuthenticatedDealsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/buyers/$id': typeof AuthenticatedBuyersIdRoute
  '/buyers/new': typeof AuthenticatedBuyersNewRoute
  '/deals/$id': typeof AuthenticatedDealsIdRoute
  '/deals/new': typeof AuthenticatedDealsNewRoute
  '/buyers': typeof AuthenticatedBuyersIndexRoute
  '/deals': typeof AuthenticatedDealsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/marketplace': typeof AuthenticatedMarketplaceRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/buyers/$id': typeof AuthenticatedBuyersIdRoute
  '/_authenticated/buyers/new': typeof AuthenticatedBuyersNewRoute
  '/_authenticated/deals/$id': typeof AuthenticatedDealsIdRoute
  '/_authenticated/deals/new': typeof AuthenticatedDealsNewRoute
  '/_authenticated/buyers/': typeof AuthenticatedBuyersIndexRoute
  '/_authenticated/deals/': typeof AuthenticatedDealsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/marketplace'
    | '/settings'
    | '/buyers/$id'
    | '/buyers/new'
    | '/deals/$id'
    | '/deals/new'
    | '/buyers/'
    | '/deals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/marketplace'
    | '/settings'
    | '/buyers/$id'
    | '/buyers/new'
    | '/deals/$id'
    | '/deals/new'
    | '/buyers'
    | '/deals'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/marketplace'
    | '/_authenticated/settings'
    | '/_authenticated/buyers/$id'
    | '/_authenticated/buyers/new'
    | '/_authenticated/deals/$id'
    | '/_authenticated/deals/new'
    | '/_authenticated/buyers/'
    | '/_authenticated/deals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketplace': {
      id: '/_authenticated/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AuthenticatedMarketplaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deals/': {
      id: '/_authenticated/deals/'
      path: '/deals'
      fullPath: '/deals/'
      preLoaderRoute: typeof AuthenticatedDealsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/buyers/': {
      id: '/_authenticated/buyers/'
      path: '/buyers'
      fullPath: '/buyers/'
      preLoaderRoute: typeof AuthenticatedBuyersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deals/new': {
      id: '/_authenticated/deals/new'
      path: '/deals/new'
      fullPath: '/deals/new'
      preLoaderRoute: typeof AuthenticatedDealsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deals/$id': {
      id: '/_authenticated/deals/$id'
      path: '/deals/$id'
      fullPath: '/deals/$id'
      preLoaderRoute: typeof AuthenticatedDealsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/buyers/new': {
      id: '/_authenticated/buyers/new'
      path: '/buyers/new'
      fullPath: '/buyers/new'
      preLoaderRoute: typeof AuthenticatedBuyersNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/buyers/$id': {
      id: '/_authenticated/buyers/$id'
      path: '/buyers/$id'
      fullPath: '/buyers/$id'
      preLoaderRoute: typeof AuthenticatedBuyersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMarketplaceRoute: typeof AuthenticatedMarketplaceRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedBuyersIdRoute: typeof AuthenticatedBuyersIdRoute
  AuthenticatedBuyersNewRoute: typeof AuthenticatedBuyersNewRoute
  AuthenticatedDealsIdRoute: typeof AuthenticatedDealsIdRoute
  AuthenticatedDealsNewRoute: typeof AuthenticatedDealsNewRoute
  AuthenticatedBuyersIndexRoute: typeof AuthenticatedBuyersIndexRoute
  AuthenticatedDealsIndexRoute: typeof AuthenticatedDealsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMarketplaceRoute: AuthenticatedMarketplaceRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedBuyersIdRoute: AuthenticatedBuyersIdRoute,
  AuthenticatedBuyersNewRoute: AuthenticatedBuyersNewRoute,
  AuthenticatedDealsIdRoute: AuthenticatedDealsIdRoute,
  AuthenticatedDealsNewRoute: AuthenticatedDealsNewRoute,
  AuthenticatedBuyersIndexRoute: AuthenticatedBuyersIndexRoute,
  AuthenticatedDealsIndexRoute: AuthenticatedDealsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
